In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [60]:
df= pd.read_csv("house_prices.csv")

In [61]:
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [62]:
df['Title'][0]

'1 BHK Ready to Occupy Flat for sale in Srushti Siddhi Mangal Murti Complex Bhiwandi'

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83079 entries, 0 to 83078
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              83079 non-null  int64
 1   Title              83079 non-null  object
 2   Description        81701 non-null  object
 3   Amount(in rupees)  83079 non-null  object
 4   Price (in rupees)  75949 non-null  float64
 5   location           83079 non-null  object
 6   Carpet Area        41618 non-null  object
 7   Status             82747 non-null  object
 8   Floor              79129 non-null  object
 9   Transaction        83051 non-null  object
 10  Furnishing         81080 non-null  object
 11  facing             50231 non-null  object
 12  overlooking        42786 non-null  object
 13  Society            27005 non-null  object
 14  Bathroom           82679 non-null  object
 15  Balcony            55913 non-null  object
 16  Car Parking        36436 non-null  object
 17  Ownership          50896 non-null  object
 18  Super Area         40727 non-null  object
 19  Dimensions         0 non-null      float64
 20  Plot Area          0 non-null      float64
dtypes: float64(3), int64(1), object(17)
memory usage: 13.3+ MB

In [64]:
df.shape

(83079, 21)

In [65]:
df.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='object')

In [66]:
df.describe()

              Index  Price (in rupees)  Dimensions  Plot Area
count  83079.000000       75949.000000         0.0        0.0
mean   41539.000000        7909.079698         NaN        NaN
std    23982.985844        4741.423164         NaN        NaN
min        0.000000          17.000000         NaN        NaN
25%    20769.500000        5250.000000         NaN        NaN
50%    41539.000000        6522.000000         NaN        NaN
75%    62308.500000        9161.000000         NaN        NaN
max    83078.000000       84619.000000         NaN        NaN

In [67]:
df.isnull().sum()

Index                    0
Title                    0
Description           1378
Amount(in rupees)        0
Price (in rupees)     7130
location                 0
Carpet Area          41461
Status                 332
Floor                 3950
Transaction             28
Furnishing            1999
facing               32848
overlooking          40293
Society              56074
Bathroom               400
Balcony              27166
Car Parking          46643
Ownership            32183
Super Area           42352
Dimensions           83079
Plot Area            83079
dtype: int64

In [68]:
df[['Amount(in rupees)','Price (in rupees)']].head(10)

  Amount(in rupees)  Price (in rupees)
0           42 Lac              6000.0
1           98 Lac             13799.0
2          1.40 Cr             17500.0
3           25 Lac                 NaN
4          1.60 Cr             18824.0
5           45 Lac              6618.0
6         16.5 Lac              2538.0
7           60 Lac             10435.0
8           60 Lac             10000.0
9          1.60 Cr             11150.0

In [69]:
import numpy as np

def convert_amount(amount):
    if isinstance(amount, str):
        amount = amount.strip()
        if 'Cr' in amount:
            return float(amount.replace('Cr', '').strip()) * 1e7
        elif 'Lac' in amount:
            return float(amount.replace('Lac', '').strip()) * 1e5
    return np.nan

In [70]:
df['Amount_numeric']= df['Amount(in rupees)'].apply(convert_amount)

In [71]:
df[['Amount(in rupees)','Amount_numeric']].head(10)

  Amount(in rupees)  Amount_numeric
0           42 Lac        4200000.0
1           98 Lac        9800000.0
2          1.40 Cr       14000000.0
3           25 Lac        2500000.0
4          1.60 Cr       16000000.0
5           45 Lac        4500000.0
6         16.5 Lac        1650000.0
7           60 Lac        6000000.0
8           60 Lac        6000000.0
9          1.60 Cr       16000000.0

In [72]:
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Amount_numeric
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,4200000.0
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,9800000.0
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,14000000.0
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,2500000.0
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,16000000.0

In [73]:
df.drop(columns=['Amount(in rupees)'],inplace=True)

In [74]:
df.drop(columns='Price (in rupees)',inplace=True)

In [75]:
df.head()

,Index,Title,Description,location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Amount_numeric
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,4200000.0
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,9800000.0
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,14000000.0
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,2500000.0
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,16000000.0

In [76]:
#  now work on title columns

import re

def  extract_bhk(title):
  if isinstance(title,str):
    pattern = r'(\d+)\s*BHK'
    match = re.search(pattern,title)
    if match:
      return int(match.group(1))
  return None

In [77]:
df['BHK']= df['Title'].apply(extract_bhk)

In [78]:
df.head()

,Index,Title,Description,location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,...,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Amount_numeric,BHK
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,...,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,4200000.0,1.0
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,...,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,9800000.0,2.0
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,...,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,14000000.0,2.0
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,...,NaN,1,1,NaN,NaN,NaN,NaN,NaN,2500000.0,1.0
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,...,TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,16000000.0,2.0

In [79]:
df['BHK'].unique()

array([ 1.,  2.,  3.,  4.,  5., nan,  6.,  8.,  7., 10.,  9.])

In [80]:
df = df.dropna(subset=["BHK"])

In [81]:
df.shape

(82431, 21)

In [82]:
df.drop(columns='Title',inplace=True)

In [83]:
missing_ratio=df.isnull().mean()*100
missing_ratio.sort_values(ascending=False)

Plot Area         100.000000
Dimensions        100.000000
Society            67.268382
Car Parking        55.822445
Super Area         50.645995
Carpet Area        50.240807
overlooking        48.127525
facing             39.106647
Ownership          38.302338
Balcony            32.896604
Floor               4.779755
Amount_numeric      3.912363
Furnishing          2.412927
Description         1.671701
Bathroom            0.460992
Status              0.399122
Transaction         0.032755
Index               0.000000
location            0.000000
BHK                 0.000000
dtype: float64

In [84]:
df.drop(columns=[
    "Plot Area",
    "Dimensions",
    "Society",
    "Super Area",
    "Car Parking",
    "Description",
    "Index"
], inplace=True)

In [85]:
df.drop(columns='Status',inplace=True)

In [86]:
df.drop(columns='Transaction',inplace=True)

In [87]:
df.head()

,location,Carpet Area,Floor,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership,Amount_numeric,BHK
0,thane,500 sqft,10 out of 11,Unfurnished,NaN,NaN,1,2,NaN,4200000.0,1.0
1,thane,473 sqft,3 out of 22,Semi-Furnished,East,Garden/Park,2,NaN,Freehold,9800000.0,2.0
2,thane,779 sqft,10 out of 29,Unfurnished,East,Garden/Park,2,NaN,Freehold,14000000.0,2.0
3,thane,530 sqft,1 out of 3,Unfurnished,NaN,NaN,1,1,NaN,2500000.0,1.0
4,thane,635 sqft,20 out of 42,Unfurnished,West,"Garden/Park, Main Road",2,NaN,Co-operative Society,16000000.0,2.0

In [88]:
def extract_area(area_str):
    if isinstance(area_str, str):
        area_str = area_str.split()[0]
        return float(area_str)
    return np.nan

In [89]:
df["Carpet_Area_sqft"] = df["Carpet Area"].apply(extract_area)

In [90]:
df.drop(columns="Carpet Area", inplace=True)

In [91]:
def extract_floor(value):
    if not isinstance(value, str):
        return None, None

    value = value.lower()

    # total floors
    if "out of" in value:
        total = value.split("out of")[1].strip()
        total = float(total)
    else:
        total = None

    # current floor
    if "lower basement" in value:
        current = -1
    elif "upper basement" in value:
        current = 0
    elif "ground" in value:
        current = 0
    else:
        try:
            current = float(value.split("out of")[0].strip())
        except:
            current = None

    return current, total

In [92]:
df[["Current_Floor", "Total_Floors"]] = df["Floor"].apply(
    lambda x: pd.Series(extract_floor(x))
)

In [93]:
df["Current_Floor"].fillna(df["Current_Floor"].median(), inplace=True)
df["Total_Floors"].fillna(df["Total_Floors"].median(), inplace=True)

In [94]:
df.drop(columns=["Floor"], inplace=True)

In [95]:
df.head()

,location,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership,Amount_numeric,BHK,Carpet_Area_sqft,Current_Floor,Total_Floors
0,thane,Unfurnished,NaN,NaN,1,2,NaN,4200000.0,1.0,500.0,10.0,11.0
1,thane,Semi-Furnished,East,Garden/Park,2,NaN,Freehold,9800000.0,2.0,473.0,3.0,22.0
2,thane,Unfurnished,East,Garden/Park,2,NaN,Freehold,14000000.0,2.0,779.0,10.0,29.0
3,thane,Unfurnished,NaN,NaN,1,1,NaN,2500000.0,1.0,530.0,1.0,3.0
4,thane,Unfurnished,West,"Garden/Park, Main Road",2,NaN,Co-operative Society,16000000.0,2.0,635.0,20.0,42.0

In [96]:
df['facing'].value_counts()

facing
East            26532
North            9243
North - East     6471
West             4666
South            2074
South -West       800
North - West      255
South - East      154
Name: count, dtype: int64

In [97]:
df["facing"] = df["facing"].str.strip().str.title()

In [98]:
df["facing"].fillna(df["facing"].mode()[0], inplace=True)

In [99]:
df.drop(columns=["overlooking"], inplace=True)

In [100]:
df["Bathroom"] = df["Bathroom"].replace("> 10", 10)

In [101]:
df["Bathroom"] = pd.to_numeric(df["Bathroom"], errors="coerce")

In [102]:
df["Bathroom"].fillna(df["Bathroom"].median(), inplace=True)

In [103]:
df["Balcony"] = pd.to_numeric(df["Balcony"], errors="coerce")
df["Balcony"]= df["Balcony"].fillna(df["Balcony"].median())

In [104]:
df.head()

,location,Furnishing,facing,Bathroom,Balcony,Ownership,Amount_numeric,BHK,Carpet_Area_sqft,Current_Floor,Total_Floors
0,thane,Unfurnished,East,1.0,2.0,NaN,4200000.0,1.0,500.0,10.0,11.0
1,thane,Semi-Furnished,East,2.0,2.0,Freehold,9800000.0,2.0,473.0,3.0,22.0
2,thane,Unfurnished,East,2.0,2.0,Freehold,14000000.0,2.0,779.0,10.0,29.0
3,thane,Unfurnished,East,1.0,1.0,NaN,2500000.0,1.0,530.0,1.0,3.0
4,thane,Unfurnished,West,2.0,2.0,Co-operative Society,16000000.0,2.0,635.0,20.0,42.0

In [105]:
df.drop(columns="Ownership",inplace=True)

In [106]:
df.drop(columns="location",inplace=True)

In [107]:
df.columns

Index(['Furnishing', 'facing', 'Bathroom', 'Balcony', 'Amount_numeric', 'BHK',
       'Carpet_Area_sqft', 'Current_Floor', 'Total_Floors'],
      dtype='object')

In [108]:
df.to_csv("clean_house_prices.csv", index=False)